[build]
  command = "npm run build"
  publish = ".next"

# Use the Next.js plugin if not already set via UI
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Let Netlify know these keys will appear publicly in the client bundle
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"

  # OPTIONAL: if you want to omit paths instead (e.g., .netlify/.next/**), you could do:
  # SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/**,.next/**"

  # NOT RECOMMENDED: disable scanning entirely
  # SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY"
